# Generated by Django 6.0.1 on 2026-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_status_remove_orderitem_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('UPI', 'UPI'), ('CARD', 'Credit / Debit Card'), ('NETBANKING', 'Net Banking'), ('WALLET', 'Wallet')], default='COD', max_length=35),
        ),
    ]
